
name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
  Xcode:
    strategy:
      matrix:
        xcode_version: ['11.4']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - uses: actions/checkout@v2
      - run: swift -version
      - run: swift package clean        
      - run: swift test -v --enable-code-coverage

  Linux:
    strategy:
      matrix:
        tag: ['5.2']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v2
      - run: swift package clean                
      - run: swift test -v --enable-test-discovery --enable-code-coverage
      - uses: mattpolzin/swift-codecov-action@0.4.0
